"""criar_tabelas_iniciais

Revision ID: 529f5bb40194
Revises: 
Create Date: 2026-07-06 14:12:20.075351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529f5bb40194'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_fiscais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chave_acesso', sa.String(length=44), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('serie', sa.String(length=10), nullable=True),
    sa.Column('cnpj_emitente', sa.String(length=18), nullable=True),
    sa.Column('cpf_emitente', sa.String(length=14), nullable=True),
    sa.Column('nome_fornecedor', sa.String(length=255), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=20), nullable=True),
    sa.Column('qtd_itens', sa.Integer(), nullable=True),
    sa.Column('origem', sa.String(length=20), nullable=True),
    sa.Column('caminho_xml', sa.String(length=500), nullable=True),
    sa.Column('caminho_pdf', sa.String(length=500), nullable=True),
    sa.Column('caminho_xml_gerado', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_entrada', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_acesso')
    )
    op.create_table('extracoes_nota',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.Column('arquivo_nome', sa.String(length=255), nullable=True),
    sa.Column('arquivo_tipo', sa.String(length=10), nullable=True),
    sa.Column('arquivo_sha256', sa.String(length=64), nullable=True),
    sa.Column('arquivo_tamanho', sa.Integer(), nullable=True),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('documento_interpretavel', sa.Text(), nullable=True),
    sa.Column('dados_sistema', sa.Text(), nullable=True),
    sa.Column('dados_llm', sa.Text(), nullable=True),
    sa.Column('dados_consolidados', sa.Text(), nullable=True),
    sa.Column('confianca', sa.Text(), nullable=True),
    sa.Column('divergencias', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('llm_status', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['nota_id'], ['notas_fiscais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_nota',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['nota_id'], ['notas_fiscais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_nota',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('ncm', sa.String(length=10), nullable=True),
    sa.Column('cfop', sa.String(length=10), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['nota_id'], ['notas_fiscais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_nota')
    op.drop_table('historico_nota')
    op.drop_table('extracoes_nota')
    op.drop_table('notas_fiscais')
    # ### end Alembic commands ###
