"""adiciona_duplicada_de

Revision ID: 5e05f932b154
Revises: 529f5bb40194
Create Date: 2026-07-06 19:41:39.408367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e05f932b154'
down_revision: Union[str, Sequence[str], None] = '529f5bb40194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas_fiscais', sa.Column('duplicada_de', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas_fiscais', 'duplicada_de')
    # ### end Alembic commands ###
